module.exports = {
  someSidebar: {
    Docusaurus: ['doc1', 'doc2', 'doc3'],
    Features: ['mdx'],
    Tutorial: [
      'tutorial/welcome-to-redwood',
      'tutorial/prerequisites',
      'tutorial/installation-starting-development',
      'tutorial/redwood-file-structure',
      'tutorial/our-first-page',
      'tutorial/a-second-page-and-a-link',
      'tutorial/layouts',
      'tutorial/getting-dynamic',
      'tutorial/cells',
      'tutorial/side-quest-how-redwood-works-with-data',
      'tutorial/routing-params',
      'tutorial/everyones-favorite-thing-to-build-forms',
      'tutorial/saving-data',
      'tutorial/administration',
      'tutorial/deployment',
      'tutorial/authentication',
      'tutorial/wrapping-up',
    ],
  },
};
